[versions]
# https://mvnrepository.com/artifact/com.android.library/com.android.library.gradle.plugin
# https://mvnrepository.com/artifact/com.android.application/com.android.application.gradle.plugin
agp = "8.13.0"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin.plugin.compose/org.jetbrains.kotlin.plugin.compose.gradle.plugin
kotlin = "2.2.21"
# https://mvnrepository.com/artifact/org.jetbrains.kotlin.plugin.serialization/org.jetbrains.kotlin.plugin.serialization.gradle.plugin
kotlinSerialization = "2.2.21"
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-core
kotlinxSerializationCore = "1.9.0"
# https://mvnrepository.com/artifact/androidx.compose/compose-bom
# https://developer.android.com/develop/ui/compose/bom/bom-mapping?hl=zh-cn
composeBom = "2025.11.00"

# android
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"

hawk = "2.0.1"

# compose
runtimeLivedata = "1.10.0-beta02"
lifecycleViewmodelCompose = "2.9.4"
navigation3Ui = "1.0.0-rc01"
adaptive = "1.2.0"
uiUnit = "1.9.4"
# https://mvnrepository.com/artifact/androidx.compose.material/material-icons-extended
materialIconsExtended = "1.7.8"

# test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

#activityCompose = "1.11.0"
#appcompat = "1.7.1"
#material = "1.13.0"
#savedstateKtx = "1.4.0"
#runtime = "1.9.4"
#workRuntimeKtx = "2.11.0"

[libraries]
# android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }

hawk = { module = "com.orhanobut:hawk", version.ref = "hawk" }

# kotlin
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose"}
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit"}
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata"}

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

# navigation3
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3Ui" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3" }

#androidx-savedstate-ktx = { group = "androidx.savedstate", name = "savedstate-ktx", version.ref = "savedstateKtx" }
#androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
#androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# compose
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
